### ISSUE TITLE
Spurious tailored products page

### ISSUE THREAD

**Issue by earnone** [c3s-magic/c3s-magic-frontend#103]
The portal contains a 'water and hydrology' page (http://portal.c3s-magic.eu/#/tailoredproducts/waterhydrology) that should have been removed when building the new portal.

I suggest we simply remove it for now.

----
The tailored product webpage has no link to WP7 diagnostics listed in the diagnostics webpage. 

Can you simply replicate the thumbnail+link of the relevant diagnostics under tailored product? E.g. rainfarm should be under water/hydrology.

**Comment by nielsdrost** [comment]
Will do (after the demo)

**Comment by nielsdrost** [comment]
Removed.
