### ISSUE TITLE
Dataviewer: image and file download do not wrk on Chrome/MacOS

### ISSUE THREAD

**Issue by sdecerff** [c3s-magic/c3s-magic-frontend#110]
Seems to apply for all layers in the file (did not try all 28 layers).

Image download pops empty browser window

File download shows error:
```
stringToDate internal error: intime is different from outtime:  "2005-12-29T14:36:19Z" != "2005-12-29T14:36:18Z"
freeDateStringToDate exception
Exception code 1
Returning from line 2059
WCS GetCoverage Request failed
```

**Comment by sdecerff** [comment]
Tested on Chrome/MacOS; On firefox it seems to be working.

**Comment by nielsdrost** [comment]
I think this was fixed (at least partially).
