### ISSUE TITLE
Write context text for climate index tailored product

### ISSUE THREAD

**Issue by nielsdrost** [c3s-magic/c3s-magic-frontend#120]

**Comment by nielsdrost** [comment]
Hello @alasdairhunter, for each tailored product we would like to have some explaination for the user. Could you create a markdown file (like for the diagnostics) with an laymen's explanation of the actuaries index?

Thanks!

**Comment by alasdairhunter** [comment]
Sorry for the slow response. Here is a vignette produced last week by Nuria at BSC:
https://earth.bsc.es/gitlab/es/s2dverification/blob/develop-Magic/vignettes/risk_index/risk_index.md

Is this what you had in mind? Maybe with more explanation of the actual index and why it was developed at the beginning?

**Comment by nielsdrost** [comment]
He @alasdairhunter,

For the metrics pages I think this is a great explanation of what the metric is for. For the tailored product page I think it is rather too technical for a non-expert user to know what is going on. I was thinking more something along the lines of the actuariesclimateindex about page: http://actuariesclimateindex.org/about/

**Comment by nielsdrost** [comment]
Done.
