### ISSUE TITLE
Site does not work in Internet Explorer

### ISSUE THREAD

**Issue by nielsdrost** [c3s-magic/c3s-magic-frontend#15]
HTML1300: Navigation occurred.
portal.c3s-magic.eu
SCRIPT438: Object doesn't support property or method 'assign'
app.e9fce8fa5d62d502696a.js (1,11815)

**Comment by maartenplieger** [comment]
Site does now render.

Login does not seem to work.

**Comment by nielsdrost** [comment]
Tried in VM Windows, seems to work for me. Login works, but needs a refresh to show button correctly. Still waiting for docker hub to catch up.

**Comment by nielsdrost** [comment]
Fixed.
