### ISSUE TITLE
Area selection in recipes settings

### ISSUE THREAD

**Issue by nperezzanon** [c3s-magic/c3s-magic-frontend#212]
Hi,

The recipes developed by BSC need settings for the area selection (maximum and minimum latitude and longitude) which, at the moment,  aren't available on the development portal (https://portal-dev.c3s-magic.eu/#/calculate/). The list of recipes which needs these settings is:

- Modes of variability
- Generic multimodel product
- Heat and cold wave duration
- Diurnal temperature variation (DTR) indicator
- Capacity factor of wind power
- Combined Climate extreme indices *
- Single and multimodel indices based on area averages 

*This current recipe name shown in the dev-portal should be modified to "Climate extreme indices" as the combination is supposed to be done with the recipe Single and multimodel indices based on area averages which input is could be the output of the previous recipe.

**Comment by nielsdrost** [comment]
Thanks! We'll have a look!

**Comment by nielsdrost** [comment]
Added these settings to these processes
