### ISSUE TITLE
ZMNAM example metric results do not show (also not in the previous metric pages)

### ISSUE THREAD

**Issue by yifatdzigan** [c3s-magic/c3s-magic-frontend#217]

**Comment by earnone** [comment]
If I read this correctly, the results from zmnam are zonal means so cannot be plotted correctly by the interactive viewer if only lon-lat maps are available. Se further comments we wrote in the [related issue](https://github.com/c3s-magic/c3s-magic-metric-status/issues/6)

**Comment by nielsdrost** [comment]
Fixed.
