### ISSUE TITLE
Keyword buttons in metrics&diagnostics main page

### ISSUE THREAD

**Issue by earnone** [c3s-magic/c3s-magic-frontend#238]
There are a number of missing keywords in the list of diagnostics:

- ZMNAM: add "WP6", "ZMNAM"
- HyInt: add "WP6", "HyInt", "calculate" (the latter when ready)
- Quantile bias: add "QuantileBias" "calculate"
- EnsClus: change order to be consistent with other dignostics
- RainFarm: add "RainFarm", "calculate"

I guess keywords for all diagnostics should have a consistent format (e.g. capital letters, order), please review as needed.

**Comment by yifatdzigan** [comment]
@earnone Done! (on a branch in the repository, waiting to be merged after all the metrics will be completed)

**Comment by earnone** [comment]
* In the metric index page, the calculate button is now present only for  CVD (to be removed or added to all others). 

* Hyint is missing tag WP6

* CVD, ESMValTool preproc, and PerfMetrics have the WP tag after the other tags. Move the WP tag as first of list.

* Toymodel does not have a WP tag
