### ISSUE TITLE
Stippling support in ADAGUC server and viewer

### ISSUE THREAD

**Issue by maartenplieger** [c3s-magic/c3s-magic-frontend#31]
First version of anomaly stippling available:

![anomaly_agreement_stippling_v0](https://user-images.githubusercontent.com/8201298/37513078-3bd79d42-2904-11e8-80dd-bd2ed65e44af.png)

**Comment by maartenplieger** [comment]
And now with slider to update stippling treshold
![anomaly_agreement_v2](https://user-images.githubusercontent.com/8201298/37517093-a3b06550-2910-11e8-9abb-9132a772daff.PNG)

**Comment by nielsdrost** [comment]
@alasdairhunter Could you have a a look (see also the live version on http://portal.c3s-magic.eu/#/demo) and see if this is what you need?

**Comment by nielsdrost** [comment]
@alasdairhunter assuming this is now done. Re-open if needed.
