### ISSUE TITLE
Basic Interactive maps

### ISSUE THREAD

**Issue by nielsdrost** [c3s-magic/c3s-magic-frontend#39]
The diagnostic page (and other pages) should include the ability to show interactive maps.

**Comment by maartenplieger** [comment]
@Faruk, if you pull the latest changes from the c3s-magic-frontend, you can do:

import ADAGUCViewerComponent from '../components/ADAGUCViewerComponent';

And in your render:
        <ADAGUCViewerComponent
          height={'50vh'}
          stacklayers={true}
          dapurl='https://localportal.c3s-magic.eu:9000/opendap/c0a5bcec-8db4-477f-930d-88923f6fe3eb/google.108664741257531327255/anomaly_agreement_20180316.nc'
          parsedLayerCallback={ (wmjsregistry) => {console.log(wmjsregistry);  this.wmjsregistry = wmjsregistry;  this.wmjsregistry.anomaly.getLayers()[0].zoomToLayer(); } }
        />
