### ISSUE TITLE
Pick a single Tailored Product

### ISSUE THREAD

**Issue by nielsdrost** [c3s-magic/c3s-magic-frontend#48]

**Comment by nielsdrost** [comment]
@maartenplieger and I think it would probably make sense to either use the actuaries index or the anomaly agreement metric. @alasdairhunter what do you think would be best?

**Comment by alasdairhunter** [comment]
Hi,
Sorry for the slow response. For tailored products I think we should use the Actuaries Index. 
Does this mean you need the namelist for this? And if yes, can I ask you to point me to some daily resolution data for either tasmax or tasmin or precipitation?

**Comment by nielsdrost** [comment]
Agree to use Actuaries index. Space for tailored products made in site, see #34 for the discussion on actual content of page.
