### ISSUE TITLE
METRIC: Anomaly Agreement

### ISSUE THREAD

**Issue by nielsdrost** [c3s-magic/c3s-magic-frontend#51]
This issue keeps track of the integration of the anomaly agreement metric into the portal

ESMValTool issue: esmvalgroup/esmvaltool#271

**Comment by nielsdrost** [comment]
Partner: BSC
Contacts: @alasdairhunter , @nmanuben 

Title: Tools to aggregate and combine multi-model climate information into a single best estimate of future climate information.

Summary (single sentence): Tools to compute the ensemble mean anomaly and the ensemble variance and agreement and plot the results as maps and time series.

Namelist in ESMValTool: anomaly_agreement.yml

Authors: Alasdair Hunter, Nicolau Manubens, Louis-Philippe Caron, Javier Vegas.

Reference: Manubens, Nicolau, Louis-Philippe Caron, Alasdair Hunter, Omar Bellprat, Eleftheria Exarchou, Neven S. Fučkar, Javier Garcia-Serrano et al. "An R package for climate forecast verification." Environmental Modelling & Software 103 (2018): 29-42.

Description of user-changeable settings on webpage:
* Selection of period for defining the climatology.
* Selection of bias correction method for computing the climatology.
* Selection of either regular, cross-validated or rescaled anomalies.
* Selection of period for projections.
* Selection of longitudes and latitudes.
* Selection of ensemble agreement threshold for stippling.
* Selection of models.
* Selection of temporal averaging (monthly, seasonal, or yearly anomalies)

Link to Screencast video: https://www.youtube.com/watch?v=CNWA4j2okcc

Description:

This diagnostic contains functions that will provide an integrated view of the historical evolution and projection of the climate system state in terms of the mean state, aggregating the multi-model data into a single signal. This diagnostic will also assess the ensemble variance and the agreement between ensemble members with the mean signal. ensemble mean anomalies for any variable with respect to its mean annual cycle computed on a pre-defined period. ensemble mean variance and agreement over any preselected period and variable of interest.

**Comment by fdiblen** [comment]
added to the diagnostics page of the portal.
