### ISSUE TITLE
Create site navigation

### ISSUE THREAD

**Issue by nielsdrost** [c3s-magic/c3s-magic-frontend#52]
The site should have a menu that reflects the new structure

**Comment by maartenplieger** [comment]
Restructured the menu, see https://github.com/c3s-magic/c3s-magic-frontend/commit/cb55362d88411f8d9988148763d4869db08ecaef
![c3s-magic-screenshot-new-menut](https://user-images.githubusercontent.com/8201298/40233053-ac2d3b5a-5aa1-11e8-8a10-2907ed5eaf87.png)

**Comment by nielsdrost** [comment]
Nice! Should we have a landing page (Home) too?
