### ISSUE TITLE
METRIC: Performance Metrics

### ISSUE THREAD

**Issue by bjoernbroetz** [c3s-magic/c3s-magic-frontend#53]
This issue keeps track of the integration of the performance metrics namelist into the portal

ESMValTool issue: esmvalgroup/esmvaltool#293

**Comment by bjoernbroetz** [comment]
Static images and description provided, see PR #94.

**Comment by nielsdrost** [comment]
@bjoernbroetz assuming this is now done. Re-open if needed.
