### ISSUE TITLE
DIAGNOSTIC: drought indicator

### ISSUE THREAD

**Issue by PeterBergSMHI** [c3s-magic/c3s-magic-frontend#68]
First simple indicator for calculating meteorological drought by consecutive dry days. Can you please assist with setting up the portal page? The yml file would look something like this:
Netcdfs for plotting are here (see instructions at the end): https://drive.google.com/drive/u/1/folders/1tUyXlsT2XY4MfBkD4H8khEsBBBVt6_Cc

---
name: Drought Indicator
partner: SMHI
authors:
  - Peter Berg
contact:
  - Peter Berg @PeterBergSMHI
description_short: |
    The drought indicator calculates diagnostics for meteorological drought.
description_long: |
    The drought indicator currently calculates indicators of meteorological drought by calculating the longest time period of consecutive dry days as well as the number of dry periods of a user defined minimum duration.
report_file: 
media: 
enableEnsembleAnomalyPlots:
reference:
  - 'Peterson, T. C., C. Folland, G. Gruza, W. Hogg, A. Mokssit, and N. Plummer, 2001: Report on the activities of the Working Group on Climate Change Detection and Related Rapporteurs 1998–2001. World Meteorological Organisation Rep. WCDMP-47, WMO-TD 1071, Geneva, Switzerland, 143 pp.'
settings:
  - Models:
      - bcc-csm1-1-m
  - Start year: 1990
  - End year: 1999
  - Experiment: Historical
  - dryindex: 'cdd'
  - Dry day limit: 1 mm/day
  - Minimum duration limit: 5 days
title: 
youtube: 

#Both of the below images are to be plotted as maps, preferrably with a "dry conditions" appeal such as the color range 'YlOrBr' from Colorbrewer (http://colorbrewer2.org/)

#Fig. 1: Plot the file CMIP5_bcc-csm1-1-m_day_historical_r1i1p1_T2Ms_pr_1990-1999_drymax.nc
#Caption: Longest period of consecutive dry days, defined as days with less than 'Dry day limit'.

#Fig. 2:
#Plot the file CMIP5_bcc-csm1-1-m_day_historical_r1i1p1_T2Ms_pr_1990-1999_dryfreq.nc
#Caption: Number of periods of more than 'Minimum duration limit'.

**Comment by nielsdrost** [comment]
Can you supply images for the netcdf files as well? I'm not sure we will be able to create an interactive map right now.

**Comment by PeterBergSMHI** [comment]
Two png images are now in the same gdrive folder as before: https://drive.google.com/drive/u/1/folders/1tUyXlsT2XY4MfBkD4H8khEsBBBVt6_Cc

**Comment by nielsdrost** [comment]
I've integrated this into the portal. Could you have a look?

http://portal.c3s-magic.eu/#/diagnostics

If you spot a typo, you can make changes in the source here: https://github.com/c3s-magic/c3s-magic-frontend/tree/master/src/static/diagnosticsdata
