### ISSUE TITLE
Implement links to metric pages

### ISSUE THREAD

**Issue by nielsdrost** [c3s-magic/c3s-magic-frontend#82]
Story: As a user, I would like be able to share a link to a metric page via email.

Diagnostics currently all share the same url (http://localhost:3000/#/diagnostics). We should add a per-metric url to allow for sharing this link.

**Comment by fdiblen** [comment]
Sharing a direct link is possible now. 

Go to --> Metrics & Diagnostics --> Select one of them and share the link.
