### ISSUE TITLE
DIAGNOSTIC: shapefile selector

### ISSUE THREAD

**Issue by PeterBergSMHI** [c3s-magic/c3s-magic-frontend#86]
A tool for selecting grid points inside a user defined polygon (by shapefile). This tool can be applied to ECVs or CIIs equally. For the demo session, an illustrative figure shows how data points are selected for different catchments in the hydrosheds data base. The figure is here: https://drive.google.com/drive/u/1/folders/11izrPDiVA5D0eovEkXwsq-9r5c3v3q0u

.yml file content:
---
name: Shapefile selection
partner: SMHI
authors:
  - Peter Berg
  - Anna Kuenz
contact:
  - Peter Berg @PeterBergSMHI
description_short: |
    Tool for selecting gridded data within a user defined polygon shapefile and outputting as NetCDF or csv file.
description_long: |
    The user provides a shapefile with one or more polygons. For each polygon, a new timeseries, or CII, is produced with only one time series per polygon. The spatial information is reduced to a representative point ('representative') or as an average of all grid points within the polygon ('mean_inside').
    If there are no grid points strictly inside the polygon, 'mean_inside' method defaults to 'representative' for that polygon.
    Outputs are in the form of a NetCDF file, or as ascii code in csv format.
report_file: 
media: 
enableEnsembleAnomalyPlots:
reference:
settings:
  - Models:
      - ERA-Interim
  - Start year: 2000
  - End year: 2000
  - Experiment: reanaly
  - shppath: 'hydrosheds/rhineselection.shp'
  - wgtmet: 'mean_inside'
  - write_csv: False
title: 
youtube: 

###
# An example output is presented in the form of the figure 'Basin_grid2.png' with the caption: 'Example of grid point selection for a river basin of the hydrosheds data base. Red points are all grid points of the model, blue points are within the two largest polygons, and the orange polygon defaults to the grid point nearest to a representative point inside the polygon, which is most often the centroid point.'

**Comment by nielsdrost** [comment]
Thanks! Could you put the picture in the MAGIC Google Drive? I seem not to be allowed to download the image you linked to.

**Comment by nielsdrost** [comment]
I've integrated this into the portal. Could you have a look?

http://portal.c3s-magic.eu/#/diagnostics

If you spot a typo, you can make changes in the source here: https://github.com/c3s-magic/c3s-magic-frontend/tree/master/src/static/diagnosticsdata
