### ISSUE TITLE
Maps showing multiple legends

### ISSUE THREAD

**Issue by nielsdrost** [c3s-magic/c3s-magic-frontend#89]
For some reason maps are showing multiple legends.

For example the correlate diagnostic:

![screenshot from 2018-06-04 21-16-57](https://user-images.githubusercontent.com/1703440/40936775-b5b872f4-683c-11e8-9dd2-ea263bf62088.png)

**Comment by maartenplieger** [comment]
This because the map controls are off (time selector, layer selector, style selector). When these are enabled via the YML file, the layers will be individually selectable.

**Comment by nielsdrost** [comment]
The yaml file (https://github.com/c3s-magic/c3s-magic-frontend/blob/master/src/static/diagnosticsdata/correlations/correlations.yml) seems to imply the settings are "on". Is this not picked up in the frontend?

enableADAGUC:
  - data_url: https://portal.c3s-magic.eu/adagucserver?source=c3smagic%2FWP6_KNMI_Correlations%2Fclimexp_correlate_output.nc&
  - projectionbutton: true
  - layerselector: true
  - timeselector: true
  - styleselector: true
  - layers: []
reference:

**Comment by nielsdrost** [comment]
Fixed by @fdiblen in frontend code. Thanks!
