### ISSUE TITLE
Metrics with missing datasets

### ISSUE THREAD

**Issue by nielsdrost** [c3s-magic/c3s-magic-frontend#97]
There are some diagnostics with missing datasets:

- [x] Stratosphere-troposphere coupling
- [x] Hydroclimatic intensity (HyInt) and extremes
- [x] Indices of annular modes
- [x] HyInt and ETCCDI trends and significance testing

It looks like the netcdf files are there (visible via autowms) but the dataviewer and diagnostic pages are not picking them up.

**Comment by earnone** [comment]
@maartenplieger @nielsdrost - I am processing the output files to correct the displaying by the viewer. I need some quick guidance and send you a few comments:
1. I do not understand why the viewer does not let you select a variable (layer?) on some files whereas it does let you select them for e.g. blocking metrics. I may then simply send you an example with one variable only.
2. I understand the viewer cannot handle timeseries, right?  I.e. 1D array only depending on time? If not or if that does not work properly how do I remove the viewer from the output page?
3. there is no title in the viewer showing the name of the variable that is plotted
4. Sending specific comments in ISAC data issue 
[https://github.com/c3s-magic/c3s-magic-portal/issues/23](https://github.com/c3s-magic/c3s-magic-portal/issues/23)

**Comment by nielsdrost** [comment]
Fixed (as far as dataviewer was able to support this)
